### ISSUE TITLE
initSessionWithLaunchOptions triggered twice

### ISSUE THREAD

**Issue by tielur** [BranchMetrics/ios-branch-deep-linking#305] opened 2016-03-07 20:26 UTC
If I click a deep link with my app not installed, then install the app and click the same deep link again the `andRegisterDeepLinkHandler` gets called twice.
 `- (void)initSessionWithLaunchOptions:(NSDictionary *)options andRegisterDeepLinkHandler:(callbackWithParams)callback;` 

Steps to Reproduce:
1. Click a deep link, get redirected to the app store
2. Install the app
3. Without opening the app go click that deep link again
4. App deeplinks and open but the `andRegisterDeepLinkHandler` gets called twice

The `callbackWithParams` are similar but different.

Example of two callback params:

The Ids are the same, but one has `+is_first_session` as true, and one has a `+referrer`. The `+click_timestamp` is also different as expected.

```
{
    "$marketing_title" = "Test Title";
    "$one_time_use" = 0;
    "+click_timestamp" = 1457381604;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 1;
    "+match_guaranteed" = 1;
    channelId = exampleChannelId;
    record = true;
    "~channel" = Affiliate;
    "~creation_source" = Dashboard;
    "~feature" = marketing;
    "~id" = 231874854297588800;
}

{
    "$marketing_title" = "Test Title";
    "$one_time_use" = 0;
    "+click_timestamp" = 1457381588;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 0;
    "+match_guaranteed" = 1;
    "+referrer" = "http://example.com/example.html";
    channelId = exampleChannelId;
    record = true;
    "~channel" = Affiliate;
    "~creation_source" = Dashboard;
    "~feature" = marketing;
    "~id" = 231874854297588800;
}
```

Thoughts on how to handle this? Is it correct that a deeplink always has the same `~id` when using a marketing link?

**Comment by ahmednawar** [comment] 2016-03-09 20:25
@tielur I couldn't reproduce on my end. Which iOS version are you testing on? Also, do you mind sending the link you are using? If you are uncomfortable sharing data here, please reach out to support@branch.io and we'll take it from there. Thanks!

**Comment by ahmednawar** [comment] 2016-03-23 00:12
@tielur any updates on this?

**Comment by SoCohesive** [comment] 2016-03-24 19:44
@ahmednawar I am experiencing the same issue. I am using iOS 9.2.1

**Comment by derrickstaten** [comment] 2016-03-24 21:29
@SoCohesive can you send over the issue Ahmed asked for? Can you provide the link you're clicking? Could you also turn on setDebug (https://dev.branch.io/getting-started/integration-testing/guide/ios/#use-debug-mode-to-simulate-fresh-installs) and send us the logs? If it makes more sense, you can send them to support@branch.io.

**Comment by tielur** [comment] 2016-03-24 22:19
@ahmednawar sorry I've been fairly busy lately, haven't been checking Github notifications. I was testing on iOS 9+ as well. I found a work around but I'd have to go dig back into my iOS application on what exactly that was. I'll try to get more information posted here within the next day or so.

**Comment by Zic0** [comment] 2016-04-01 11:16
@tielur During your onboarding process do you ask for permissions ?
It might be that https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/issues/210.

**Comment by tielur** [comment] 2016-04-01 23:16
@Zic0 my app is structured very similar to how the [Branchster iOS Example App](https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-iOS) is structured.

```ObjC
Branch *branch = [Branch getInstance];

[branch initSessionWithLaunchOptions:launchOptions
                            andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error)
    {
        // code here...
    }
```

**Comment by tielur** [comment] 2016-04-01 23:22
@Zic0 ahh if you ask for any iOS permissions it triggers #210 

Yes I am asking for location permissions during the on boarding process, and I can confirm that after you allow this permission the `initSessionWithLaunchOptions` method gets called. So it may have been related to that.

**Comment by ahmednawar** [comment] 2016-04-04 23:23
@tielur does the solution provided in #210 work for you?

**Comment by ahmednawar** [comment] 2016-04-29 00:23
@tielur any updates here? would love to help

**Comment by tielur** [comment] 2016-04-29 00:56
@ahmednawar I resolved this in a different way, but it's definitely related to #210 when I was experiencing it.

**Comment by ahmednawar** [comment] 2016-04-29 03:16
@tielur great. I'll close here. Feel free to reopen if anything comes up

**Comment by Fosile** [comment] 2016-12-12 12:49
I am experiencing the same issue. I check at every App start, if there is a some DeepLink Data and open a specific Controller or the default Controller. But no matter what, everytime my Controller is fully loaded, i ask for Push and Location Permission, and for each Permission  the `initSessionWithLaunchOptions` is called again. So its get called 3 time in a row!

**Comment by E-B-Smith** [comment] 2016-12-12 19:04
I am going to re-open this issue since it was never really resolved before.  It's related to issue #210.
 
@ahmednawar Can you provide your solution for this to @Fosile? Hopefully it will get them going until we provide a real fix for this.

**Comment by Fosile** [comment] 2016-12-13 14:30
This is my Code and especially `[self handleDefaultAppStart:launchOptions]` is called way too often, also when the app comes from background to foreground and also when i ask for Permission.

```
- (void) initializeBranch: (NSDictionary *) launchOptions {
    
    Branch *branch = [Branch getTestInstance];
    
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        
        //We have Depp Link Data
        if (!error && (params[@"objectId"]) && (params[@"objectTypeId"])) {
            
            [self cleanReferrerSettings];
            
            referrerFlag = YES;
            
            self.referrerParams = [NSDictionary new];
            self.referrerParams = params;
            
            NSUserDefaults *userSettings = [NSUserDefaults standardUserDefaults];
            NSMutableDictionary *mutableRetrievedDictionary = [NSMutableDictionary new];
            
            [mutableRetrievedDictionary setValue:[self.referrerParams objectForKey:@"objectId"] forKey:@"objectId"];
            [mutableRetrievedDictionary setValue:[self.referrerParams objectForKey:@"objectTypeId"] forKey:@"objectType"];
            
            [userSettings setValue:mutableRetrievedDictionary forKey:@"referrerObjects"];
            
            [userSettings synchronize];
            
            NSLog(@"params: %@", params.description);
            
            [self handleDeepLinkAppStart];
            
            //There is no Deep Link Data and no Error
        } else if(!error && !(params[@"objectId"])) {
            
            [self handleDefaultAppStart:launchOptions];
            
            //Error occurred or Timeout
        } else if(error) {
            
            NSLog(@"BRANCH ERROR OR TIMEOUT");
        }
    }];
}
```

**Comment by E-B-Smith** [comment] 2016-12-13 16:27
The additions to your code may solve your problem.  They're commented with 'Branch':

```objc
- (void) initializeBranch: (NSDictionary *) launchOptions {
    
    static BOOL wasInitialized = NO;  //  Branch -- Add this line.
    Branch *branch = [Branch getTestInstance];
    
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        
        //We have Depp Link Data  <== From Johnny Depp? Cool!  -- Branch.
        if (!error && (params[@"objectId"]) && (params[@"objectTypeId"])) {
            
            [self cleanReferrerSettings];
            
            referrerFlag = YES;
            
            self.referrerParams = [NSDictionary new];
            self.referrerParams = params;
            
            NSUserDefaults *userSettings = [NSUserDefaults standardUserDefaults];
            NSMutableDictionary *mutableRetrievedDictionary = [NSMutableDictionary new];
            
            [mutableRetrievedDictionary setValue:[self.referrerParams objectForKey:@"objectId"] forKey:@"objectId"];
            [mutableRetrievedDictionary setValue:[self.referrerParams objectForKey:@"objectTypeId"] forKey:@"objectType"];
            
            [userSettings setValue:mutableRetrievedDictionary forKey:@"referrerObjects"];
            
            [userSettings synchronize];
            
            NSLog(@"params: %@", params.description);
            
            [self handleDeepLinkAppStart];
            
            //There is no Deep Link Data and no Error
        } else if(!error && !(params[@"objectId"])) {
            
            if (!wasInitialized) {   //  Branch -- Add this
               [self handleDefaultAppStart:launchOptions];
            }
            //Error occurred or Timeout
        } else if(error) {
            
            NSLog(@"BRANCH ERROR OR TIMEOUT");
        }
       wasInitialized = YES;  // Branch -- And add this.  
    }];
}
```

**Comment by Fosile** [comment] 2016-12-14 09:12
Thank you very much for the quick response. Simple but effective. Everything is working as expected now!

**Comment by E-B-Smith** [comment] 2016-12-14 15:57
Glad it works!

**Closed by E-B-Smith** 2016-12-14 15:57 UTC

**Comment by pallaviashim** [comment] 2017-09-29 20:05
Hello,

We have our iOS app. And I can link our app from our online site in chrome. But when i run the app again (or launch it from background), the branch api returns the same params( but two less) when it is deep linked. 

Found that the first time deeplink handler is getting fired twice. When first time it fires, the params doesnt have the key "_branch_match_id" and on going background and coming up they are sending params with "_branch_match_id".

Also i noticed that the handler method getting called twice in some cases. In that case too, the "_branch_match_id" is missing in the first and the second time they are sending the full set of keys.

Do you have a fix?

Thanks

**Comment by E-B-Smith** [comment] 2017-09-29 21:13
Is this a Chrome specific problem, or do you see it in Safari too?

Which version of the iOS SDK are you running?

**Comment by pallaviashim** [comment] 2017-10-02 16:32
I didnt find this issue in safari.
And I am getting the issue in both iOS 10 and iOS 11. I haven't checked in other versions.

**Comment by E-B-Smith** [comment] 2017-10-03 16:25
I could not reproduce this with Chrome on iOS 10 or 11 using the Branch TestBed app.

Every time your app becomes active it will start a new Branch session, even if there's no new URL to open (Branch still needs to check that there's no new URL).

If you still have an issue with Chrome and Branch, open a new issue or contact support at Branch (the support team is pretty good!) and include some more details specific to your use case.

**Comment by animeshp** [comment] 2019-07-03 05:35
I'm facing this issue with the latest Branch SDK in a very specific scenario. `initSession(launchOptions: launchOptions)` is being called twice. **Steps to reproduce:**:

1. Install the app on device through Xcode.
2. Open the app.
3. Kill it.
4. Click on deep link from Notes or Messages app.
5. `initSession(launchOptions: launchOptions)` called twice. First time `+clicked_branch_link` is `true` and second time `+clicked_branch_link` is `false`.

Any directions to fix this?

Thanks

**Comment by ahmednawar** [comment] 2019-07-04 06:03
cc @echo-branch

**Comment by echo-branch** [comment] 2019-07-05 19:34
@animeshp 
Please file a support ticket.  I was unable to repro with v0.27.1 on iOS 12.3.1.

**Comment by animeshp** [comment] 2019-07-08 17:31
@echo-branch  I've already filed a support ticket. It is no. 81678.
