### ISSUE TITLE
Use of '@import' when C++ modules are disabled, consider using fmodules and fcxx

### ISSUE THREAD

**Issue by Fosile** [BranchMetrics/ios-branch-deep-linking#730] opened 2017-10-05 12:38 UTC
When i´m updating the branch SDK to 0.19.5 (was 0.17.10) and try to run my App, i get the following Errors:

![bildschirmfoto 2017-10-05 um 14 27 55](https://user-images.githubusercontent.com/5736296/31227511-628ed328-a9da-11e7-96a5-c960472d80ac.png)

![bildschirmfoto 2017-10-05 um 14 28 09](https://user-images.githubusercontent.com/5736296/31227559-83209bb2-a9da-11e7-99e5-f726f485eb31.png)

After a downgrade to 0.17.10, everything works fine again!

I´m using Xcode 9.0.

**Comment by E-B-Smith** [comment] 2017-10-05 17:12
Have you tried turning on `fmodules` and `fcxx-modules`? I know that the C++ clang now supports modules, but there may be some downsides that I don't know about.  

I am curious about this too, so I will experiment with this on my end to see what's up.

The module imports help a lot with Swift integration, which many people really like. But if this is a blocker for C++ I can hopefully figure out an alternative that makes everybody happy.

**Comment by E-B-Smith** [comment] 2017-10-06 15:05
Is there a  particular C++ library in you are compiling?  I want to make a sample app to reproduce this so I understand it better.

**Comment by E-B-Smith** [comment] 2017-10-12 17:44
I'd like to hear why modules won't work for you. Rather than implement a quick fix that might work I'll close this issue until there is more information.

**Comment by podkovyrin** [comment] 2017-11-01 10:21
Hello @E-B-Smith! We're facing the same issue. And it seems to be the case: https://stackoverflow.com/a/36307557/2830525
We're using C++ pods (`dlib` for instance) in our project inside Objective-C++ files. So it leads to disabling modules in spite of build settings.

**Comment by E-B-Smith** [comment] 2017-11-01 15:41
Great -- I'll look into it.  This is the sort of background information I needed to investigate this.

**Comment by E-B-Smith** [comment] 2017-11-04 22:54
This will be fixed in the next release, Branch 0.21.

**Comment by E-B-Smith** [comment] 2017-11-21 18:23
Fixed in SDK version 0.21.11.

**Closed by E-B-Smith** 2017-11-21 18:23 UTC
Labels: ready for release
