### ISSUE TITLE
Open app via link - custom params dictionary is wrong

### ISSUE THREAD

**Issue by shmakovigor** [BranchMetrics/ios-branch-deep-linking#456] opened 2016-09-18 14:58 UTC
Hi! I run into an issue that when I launch my app via link params dictionary contains only 2 keys:

{
    "+clicked_branch_link" = 0;
    "+is_first_session" = 0;
}

and doesn't contain my custom metadata:

```
let branch = Branch.getInstance()
branch?.initSession(launchOptions: launchOptions) { params, error in

}
```

But when I press the same link when app is already launched params dictionary contains my metadata.

Any ideas why this happens? I use the latest SDK and iOS 10.
Thanks in advance!

**Comment by aaustin** [comment] 2016-09-18 17:47
Hey @shmakovigor - I know you said this, but I wanted to confirm you're using the latest 0.12.10. I ask because we patched an issue related to the exact behavior you're seeing in 0.12.10.

Second, is this Universal Link behavior? As in, you're clicking the link from notes or messages and the app is opening directly?

Lastly, confirming you have the Branch calls `initSession` in `didFinishLaunching`, `handleDeepLink` in `openUrl` and `continueUserActivity` in `continueUserActivity` for the App Delegate.

**Comment by shmakovigor** [comment] 2016-09-18 17:55
1) Yes - I've just checked and I can confirm that I use 0.12.10 version.
2) Yes, this is Universal Link behaviour and app is opening directly

**Comment by shmakovigor** [comment] 2016-09-18 18:41
I debug source code and noticed that method ```processResponse:error:``` of class BranchOpenRequest in most cases return following response:

**Comment by derrickstaten** [comment] 2016-09-19 18:19
@shmakovigor I'm unable to reproduce your issue on 0.12.10. Can you post the request logs, or send them to derrick@branch.io? Thanks

**Comment by derrickstaten** [comment] 2016-09-19 18:47
@shmakovigor I'm now able to reproduce after quite a lot of testing. It seems that `universal_link_url` is missing from the v1/open request in some cases. I'm looking into this now.

**Comment by shmakovigor** [comment] 2016-09-19 20:56
@derrickstaten you are right! ```universal_link_url``` is missing from https://api.branch.io/v1/open request. Just have checked it.

**Comment by derrickstaten** [comment] 2016-09-19 22:10
@shmakovigor https://github.com/BranchMetrics/ios-branch-deep-linking/pull/460. it seems that swift -> objective c inter-op is pretty broken around the edges.

**Comment by shmakovigor** [comment] 2016-09-20 09:41
So is there any workaround to make it work?

**Comment by shmakovigor** [comment] 2016-09-20 10:32
@derrickstaten Well, I found temporary workaround:

```
let branch = Branch.getInstance()
        
branch?.initSession(launchOptions: (launchOptions as! NSDictionary) as! [AnyHashable : Any]) { params, error in

}
```

Looks nasty, but works.

**Comment by derrickstaten** [comment] 2016-09-20 16:06
@shmakovigor hmm, I'm intrigued by that solution, as it means we would not need to change SDK code (and deprecate our accountForFacebookSDK feature). 

Let me discuss with the team.

**Comment by aaustin** [comment] 2016-09-26 15:45
Hey @shmakovigor - the latest SDK (`0.12.11`) has a fix for this issue. You can stop calling `accountForFacebookSDK` and just make sure that you return true in didFinishLaunching all the time.

**Closed by aaustin** 2016-09-26 15:45 UTC
