### ISSUE TITLE
Branch deep links from "Test" account never open staging build installed on device - always redirect to AppStore

### ISSUE THREAD

**Issue by maximkhatskevich** [BranchMetrics/ios-branch-deep-linking#357] opened 2016-05-24 13:39 UTC
We are using the same custom domain for both Live and Test accounts. Also we use the same bundle ID for both staging and production builds. Of course, in the app, when it's a staging build, it uses Test Branch key, when it's a prod build - it uses Live Branch key.

Expected workflow is like this:
- install and run staging build on device (run from Xcode or install AdHoc build from HockeyApp);
- quit staging build;
- go to Messages, click on a deep link there (the link created under Test account on Branch dashboard);
- iOS redirects straight to the app.

Fact workflow is like this:
- install and run staging build on device (run from Xcode or install AdHoc build from HockeyApp);
- quit staging build;
- go to Messages, click on a deep link there (the link created under Test account on Branch dashboard);
- iOS redirects to the App Store page of our app.

Please, help. How it is supposed to test/debug deep links functionality before release to App Store?

**Comment by ahmednawar** [comment] 2016-05-24 16:46
@maximkhatskevich I've seen your ticket that you sent to support@branch.io. I'm copying this information to the ticket and closing here.

**Closed by ahmednawar** 2016-05-24 16:46 UTC

**Comment by maximkhatskevich** [comment] 2016-05-24 17:09
Okay, thanks! Will reply by email shortly.

**Comment by ahmednawar** [comment] 2016-05-24 18:48
We completed this discussion off Github and the issue is a DNS config with a custom domain that is preventing the apple-app-site-association file from being served via HTTPS

**Comment by zanemcca** [comment] 2016-05-24 21:38
@ahmednawar Would you mind elaborating? I am having this same issue.

**Comment by zanemcca** [comment] 2016-05-24 21:42
It only seems to happen when clicking thru from Facebook or FB Messenger.
Messages, Gmail and Email seem to work fine

**Comment by ahmednawar** [comment] 2016-05-24 21:45
@zanemcca This is a different issue. Unfortunately, Facebook doesn't support Universal Links and their redirection is broken if the app is not installed, so we always fallback to the App Store. One workaround is showing a Deepview for Facebook where the CTA button will act as a Universal Link.

**Comment by zanemcca** [comment] 2016-05-24 21:49
@ahmednawar it continues to open the App Store even after I the app has been installed. Any ideas on how to fix that?

**Comment by ahmednawar** [comment] 2016-05-24 21:53
@zanemcca This is the expected behavior. We can't open the app and fallback to the App Store is the app is not installed because of Facebook's redirection. We could use a Deepview to work around this limitation.

**Comment by zanemcca** [comment] 2016-05-24 22:14
@ahmednawar I tried the [Website to App Routing](https://dev.branch.io/features/website-to-app-routing/overview/) technique and I also tried the [Branch Monster Factory](https://itunes.apple.com/ca/app/branch-monster-factory/id917737838?mt=8) example app and both still route through App Store when clicking from the deepview/website. Is this still the expected behaviour? Does Branch not integrate with [Facebook App Links](https://developers.facebook.com/docs/applinks)?

**Comment by ahmednawar** [comment] 2016-05-25 19:16
We continued this convo via email. Here is our response:

> We actually do inject the App Links tags to our links but the problem though is that Facebook ads are superior to organically shared links. Facebook doesn't implement deferred deep linking scenarios for regular links the same way they do for ads. There is a meta tag that you can set (an additional AL tag) on the links to force it not to open any webpage and this will open the app if installed. However, when the app is not installed, Facebook will show a modal with the App Store but not record a click or report anything to our servers. In this case we won't be able to match the user or provide attribution. In short, deferred deep linking for organic posts is completely broken if you use App Links.
> 
> As you can see, none of the solutions are perfect unfortunately. I want to clarify something regarding Deepviews. If the app is installed, you will see the webpage and when clicking on the CTA button, you will go directly to the app not the App store and without showing any popup from Facebook.
