### ISSUE TITLE
Cannot install with Carthage anymore

### ISSUE THREAD

**Issue by racer1988** [BranchMetrics/ios-branch-deep-linking#737] opened 2017-10-17 13:29 UTC
Failed to write to /../Carthage/Build/iOS/Branch.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Branch.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file://////Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build/ArchiveIntermediates/Branch%20iOS%20SDK%20Carthage/BuildProductsPath/Release-iphoneos/Branch.framework, NSFilePath=/Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build/ArchiveIntermediates/Branch iOS SDK Carthage/BuildProductsPath/Release-iphoneos/Branch.framework, NSUnderlyingError=0x7ff20f58c990 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by nwhanan** [comment] 2017-10-17 18:58
I'm getting the same issue, you can generate the error by running:

`carthage build --no-skip-current`

My knowledge of the internals of Carthage is limited, so I have not been able to determine the root cause as of yet.

**Comment by jdee** [comment] 2017-10-17 19:00
I've been building successfully with Carthage quite a bit in the last couple of days, using 0.19.5. Can you try `carthage update` instead of `carthage build`?

**Comment by E-B-Smith** [comment] 2017-10-17 19:11
Are you getting a "framework not found FileProvider for architecture x86_64" error?

**Comment by nwhanan** [comment] 2017-10-17 19:27
@jdee  The error has been intermittent for me occasionally.  I discovered the issue when running `carthage update` originally, and was following **Resolve Build Failures** section of the Carthage Readme.

@E-B-Smith I am not seeing a FileProvider error so far.

**Comment by racer1988** [comment] 2017-10-17 19:39
@jdee I have the issue using 0.19.5
I get the issue with both
`carthage update` and `carthage bootstrap`

I updated `carthage` to the latest version.

@E-B-Smith I am not getting that error, the whole output I get in CLI is the one I posted.
I can retrieve the logs if needed

**Comment by nwhanan** [comment] 2017-10-17 19:43
The Xcode build log from carthage doesn't show anything out of the ordinary, it reports that the `** BUILD SUCCEEDED **`.  It seems be something right after that.

**Comment by E-B-Smith** [comment] 2017-10-17 19:52
@racer1988 Can you send the log? It would be super useful.

I have a few test projects I use to make sure that Carthage integrates correctly. I'll test with those to see if I can reproduce the error.

**Comment by racer1988** [comment] 2017-10-17 22:35
Running:

`carthage bootstrap --platform ios --no-use-binaries --cache-builds`

[xcrun.log](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1392835/xcrun.log)

I don't see any issue in the build.

However Carthage stops executing:

```
*** Building scheme "Branch iOS SDK Carthage" in BranchSDK.xcodeproj
Failed to write to /Users/xxx/Developer/xxx/Carthage/Build/iOS/Branch.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Branch.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/xxx/Developer/xxx/Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build/ArchiveIntermediates/Branch%20iOS%20SDK%20Carthage/BuildProductsPath/Release-iphoneos/Branch.framework, NSFilePath=/Users/xxx/Developer/xxx/Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build/ArchiveIntermediates/Branch iOS SDK Carthage/BuildProductsPath/Release-iphoneos/Branch.framework, NSUnderlyingError=0x7fd4a06602a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by jdee** [comment] 2017-10-17 22:46
@racer1988 Can you verify that this directory exists? `/Users/xxx/Developer/xxx/Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build/ArchiveIntermediates/Branch iOS SDK Carthage/BuildProductsPath/Release-iphoneos`

It's trying to write out a new file and complaining that it doesn't exist. That often happens when a path component is missing. Maybe if we can see where the path ends, that will shed some light on the problem.

**Comment by jdee** [comment] 2017-10-18 00:57
I think this may be happening because the repo was renamed in the past, and maybe all the appropriate redirects aren't working. https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK redirects here, but I've had problems in other repos with shields in READMEs and so on.

Can you try this instead:

```
github "BranchMetrics/ios-branch-deep-linking" "0.19.5"
```

or 

```
git "https://github.com/BranchMetrics/ios-branch-deep-linking" "0.19.5"
```

I suspect that will fix the issue.

**Comment by nwhanan** [comment] 2017-10-18 03:44
Mine already uses that one, though I leave out the version number so it will see updates outside of the minor version number.

The line from my Cartfile is:
`github "BranchMetrics/ios-branch-deep-linking"`

**Comment by atetlaw** [comment] 2017-10-18 04:45
I have the same issue. There were some recent Carthage changes, and I've opened an issue there too: https://github.com/Carthage/Carthage/issues/2220

**Comment by racer1988** [comment] 2017-10-18 07:59
@jdee  `ArchiveIntermediates` is missing 
```
$ ll .../Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/Build
total 0
drwxr-xr-x@ 4  -  136B Oct 18 00:27 ./
drwxr-xr-x  5  -  170B Oct 18 00:26 ../
drwxr-xr-x@ 5  -  170B Oct 18 00:27 BranchSDK.build/
drwxr-xr-x  4  -  136B Oct 18 00:27 Release-iphonesimulator/
```

**Comment by ikesyo** [comment] 2017-10-18 15:27
See my comments there:

- https://github.com/Carthage/Carthage/issues/2220#issuecomment-337612613
- https://github.com/Carthage/Carthage/issues/2220#issuecomment-337629280

**Comment by jdee** [comment] 2017-10-18 16:53
Thanks for the suggestion, @ikesyo. I was able to reproduce the bug, and that seemed to fix it. See #738. You can try it for now to see if it solves your problem using `github "BranchMetrics/ios-branch-deep-linking" "fix-carthage"`. This will be reviewed and released soon.

**Comment by nwhanan** [comment] 2017-10-19 00:41
@jdee @E-B-Smith Since the "fix-cartage" branch has been closed already, I tried it with the staging branch that it appears to be merged into, and it compiled fine with Carthage.

Thanks for looking into this, and particularly to @ikesyo for the information about `SYMROOT`.

**Comment by E-B-Smith** [comment] 2017-10-19 01:47
This fix has merged to master.  Thanks for all the info.

**Closed by E-B-Smith** 2017-10-19 01:47 UTC
