### ISSUE TITLE
[BNCPreferenceHelper universalLinkUrl]

### ISSUE THREAD

**Issue by danielnagyx** [BranchMetrics/ios-branch-deep-linking#753] opened 2017-11-13 12:57 UTC
Hi!

One of our users experienced a constant crash coming from `[BNCPreferenceHelper universalLinkUrl]`.  It results in a `EXC_BAD_INSTRUCTION 0x00000000761f3a25` and every time the app is restarted it will crash when the Branch SDK is initialized and trying to access `[BNCPreferenceHelper universalLinkUrl]` again.

The SDK version is 0.18.8

Here is the stacktrace:
```Crashed: com.apple.main-thread
0  App                            0x1014a548c -[BNCPreferenceHelper universalLinkUrl] (BNCPreferenceHelper.m:348)
1  CoreFoundation                 0x18647e12c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
2  CoreFoundation                 0x18647d6cc _CFXRegistrationPost + 420
3  CoreFoundation                 0x18647d430 ___CFXNotificationPost_block_invoke + 60
4  CoreFoundation                 0x1864fa9f4 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
5  CoreFoundation                 0x1863b43e0 _CFXNotificationPost + 380
6  Foundation                     0x186dd4498 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
7  UIKit                          0x18f97d708 -[UIApplication _stopDeactivatingForReason:] + 1292
8  UIKit                          0x1902d6a5c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 376
9  UIKit                          0x19046bfc8 _performActionsWithDelayForTransitionContext + 112
10 UIKit                          0x1902d6870 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 252
11 UIKit                          0x1900c0850 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 364
12 UIKit                          0x18ff65bd8 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468
13 FrontBoardServices             0x188b8e21c __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212
14 libdispatch.dylib              0x185e71048 _dispatch_client_callout + 16
15 libdispatch.dylib              0x185e786c8 _dispatch_block_invoke_direct$VARIANT$mp + 288
16 FrontBoardServices             0x188bc1a04 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
17 FrontBoardServices             0x188bc16a8 -[FBSSerialQueue _performNext] + 404
18 FrontBoardServices             0x188bc1c44 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
19 CoreFoundation                 0x186494358 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20 CoreFoundation                 0x1864942d8 __CFRunLoopDoSource0 + 88
21 CoreFoundation                 0x186493bb4 __CFRunLoopDoSources0 + 288
22 CoreFoundation                 0x186491738 __CFRunLoopRun + 1048
23 CoreFoundation                 0x1863b22d8 CFRunLoopRunSpecific + 436
24 GraphicsServices               0x188243f84 GSEventRunModal + 100
25 UIKit                          0x18f95f880 UIApplicationMain + 208
26 App                            0x101281258 main (main.m:12)
27 libdyld.dylib                  0x185ed656c start + 4

**Comment by E-B-Smith** [comment] 2017-11-14 16:28
I think that this is caused by a race condition that I fixed in version 0.21.2.

**Closed** 2017-11-14 16:34 UTC
