### ISSUE TITLE
No way to clear cookies

### ISSUE THREAD

**Issue by gsabran** [BranchMetrics/ios-branch-deep-linking#503] opened 2016-11-11 20:52 UTC
There's no way to clear the cookies, meaning the deep link that have been intended to be opened. This is an issue in situations like:

- a link is clicked that opens a web view that sets a cookie to go to item A, but the app is not opened
- a link is clicked and directly open the app to item B. This will link to item B, and won't clear the past intent to go to item A. So the link to item A will be trigger after which is confusing and hard to handle well.

**Comment by E-B-Smith** [comment] 2016-11-11 22:39
Let me look into this.  Can you give me a few more details?

Are these the same kind of links?  Is the first a universal link and second an app scheme link (a link like myapp://open?link_click_id=...)?

Are these clicks rapid fire back-to-back, or is there a little time between them?

**Comment by gsabran** [comment] 2016-11-12 00:59
Both are universal links. One is coming from what I think is a cookie set when going to the deepview, and the other is passed directly at app launch when opening the app from a link in iMessage. There's a little time in between. Like not a lot but it's definitively not happening back to back. My best guess is that the cookie is retrieved with some delay, and probably asynchronously (you probably know better) and that the direct opening doesn't clear the cookie.

I'd except the app to only have one pending deep link at a time (which is the case with cookie based ones since going to a deep view removed the previous intent if any) but here it's not the case.

**Comment by E-B-Smith** [comment] 2016-11-14 19:21
Your expectations are correct -- Only the most recent deep link should be handled.

I'm not able to reproduce your problem immediately.  I'll try a few other things too.  Maybe something weird is happening in iMessage.

**Comment by aaustin** [comment] 2016-11-23 23:49
Hey @gsabran - I wanted to chime in on your use case here. It's not a problem with this library, so I'm going to close this issue out. It's more a function of how the Branch deferred deep linking system works. We don't refer to them as "cookies" for the click, we refer to them as "outstanding matches". If you think this is a common use case for you, we actually give you the ability to control the duration of how long a match will remain outstanding. Our default is two hours, but you could lower this to 5 minutes if you were super concerned about it. You can control it at a global level or on a per link basis. Please review highlighted section at the bottom of these docs for more info: https://dev.branch.io/getting-started/matching-accuracy/overview/

**Closed by aaustin** 2016-11-23 23:49 UTC
Labels: needs review

**Comment by gsabran** [comment] 2016-11-28 22:05
Ok thanks for the clarification. But it seems unexpected that handling one outstanding match won't remove other matches that might be less outstanding, which is what I think @E-B-Smith was mentioning.

**Comment by aaustin** [comment] 2016-12-04 00:37
I see your point and it's a valid one. To do this, we'd need to confident that the outstanding click (tied to a cookie) is associated with the native app session (IDFA) is the same person. We have the data to do this a certain percentage of the time. However, this whole double outstanding match should hopefully be a pretty rare scenario. Let me add this request to our infra backlog in the mean time. Thanks!
