### ISSUE TITLE
Incorrect universal link handling after killing the app

### ISSUE THREAD

**Issue by elikohen** [BranchMetrics/ios-branch-deep-linking#366] opened 2016-06-07 14:47 UTC
Hello branch team, i'm an iOS developer at Letgo, we've found a bug that causes some universal links to be ignored when clicked and launched again next time the user opens the app:

Process to reproduce the bug:

1. Init the app:
	- With a http proxy we see branch sdk calls `open` in branch api
	- We call `branch.initSessionWithLaunchOptions(launchOptions, andRegisterDeepLinkHandlerUsingBranchUniversalObject` inside `func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool`

2. double click home button on device and 'kill' the app (swiping it) + go to dashboard  (this step cause a bug on ios that calls `willEnterForeground` and then `didBecomeActive` but the app never actually became active so it won't call `willEnterForeground` again)
	- we see the `close` api call in branch api 
	- we also see a new `open` api call (this one breaks everything)

3. click a universal link
	- App launches (we call the init session again)
	- App receives `func application(application: UIApplication, continueUserActivity userActivity: NSUserActivity, restorationHandler: ([AnyObject]?) -> Void) -> Bool` and we pass it to branch
	- There's NO `open` call
	- We receive the BranchUniversalObject callback with `nil` -> Problem

4. We go to background (or click power button)
	- App calls `close` branch api

5. We open again the app (or unlock the screen)
	- App calls `open` with the deeplink from step 3 (this one is a bit wtf for us)
	- We receive the Branch universal object callback and execute the action -> Problem because this time the user didn't click anything and we're redirecting him to a new screen.

I hope this helps you to find the error.  Thanks

**Comment by ahmednawar** [comment] 2016-06-09 05:43
@elikohen Thanks for such a thorough description! I'm unable to reproduce and it's probably because I am not clear on the dashboard part in step #2. Which dashboard are you talking about? I assumed you meant the Notification center on iOS but this didn't work. 

Could you please clarify step #2 so that I could reproduce on my end? Thanks!

**Comment by elikohen** [comment] 2016-06-09 06:43
Hello there! you're right, 'dashboard' is not clear at all sorry.
I meant clicking where all the apps icons are, so you just double click home, swipe out the app and then click on the right edge to go to see all the apps.

**Comment by ahmednawar** [comment] 2016-06-13 20:45
@elikohen Thanks for the clarification. Unfortunately, I still can't reproduce. Would it be possible to record a video of this happening? Also, do you have a link for the iOS bug you mentioned?

**Comment by ahmednawar** [comment] 2016-06-30 23:39
@elikohen any updates on this issue? Would love to help and sort it out.

**Comment by ahmednawar** [comment] 2016-07-29 16:51
Closing here, feel free to re-open if you have any updates.

**Comment by d-krueger** [comment] 2016-09-02 12:18
Hi,
have you been able to fix this? I have a similar issue.

**Comment by ahmednawar** [comment] 2016-09-02 23:16
@d-krueger Could you please send us steps to reproduce plus the expected outcome?

**Comment by d-krueger** [comment] 2016-09-05 08:26
Hi @ahmednawar 
since I'm using the react native branch implementation I posted a more elaborate problem description here:

[https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/40](url)

**Comment by aaustin** [comment] 2016-09-05 17:01
Let's close this and follow the thread on that repo, since it's likely related to to the wrapper.

**Closed by aaustin** 2016-09-05 17:01 UTC
