### ISSUE TITLE
Various Swift compile errors with new build 0.12.6

### ISSUE THREAD

**Issue by francisjervis** [BranchMetrics/ios-branch-deep-linking#418] opened 2016-08-31 07:13 UTC
Mostly in AppDelegate methods, at least in my implementation.

1: Error logging using NSLog from the init method thus
````
branch.initSessionWithLaunchOptions(launchOptions, andRegisterDeepLinkHandler: { params, error in
if error != nil {
   NSLog("%@", error!)
}
````
now generates a "Variadic function is unavailable" error. 
This is a known issue with Swift:
https://bugs.swift.org/browse/SR-1478
but logging these errors with NSLog worked prior to this update and is desirable. Note that 
     NSLog("%@", error as! NSObject)
generates a message that "cast from NSError? to unrelated type NSObject always fails."

2:
    `if params != nil {`
within the same method now raises a "comparison isn't allowed" error.

3: Various "cannot use optional chaining on non-optional value" errors working with the params dictionary now, see image. 

<img width="608" alt="screen shot 2016-08-31 at 12 11 06 am" src="https://cloud.githubusercontent.com/assets/10519862/18119715/d60a81fe-6f10-11e6-85b7-f25fa4230e96.png">

I suspect this is related to the nullability changes in this release but I am surprised it is breaking existing code like this. The logging is a relatively minor issue but the other 2 are quite undesirable as the "optional chaining" logic is rather crucial to the routing method I have right now!

**Comment by ahmednawar** [comment] 2016-08-31 07:24
@francisjervis Thanks for reporting. I don't see the image you are referring to. Am I missing something here?

**Comment by francisjervis** [comment] 2016-08-31 07:25
That's odd. Link: https://cloud.githubusercontent.com/assets/10519862/18119715/d60a81fe-6f10-11e6-85b7-f25fa4230e96.png

**Comment by francisjervis** [comment] 2016-08-31 07:32
What appears to have happened is that the nullability changes in #368 + #411 are somehow making it impossible to check if a key-value pair exists in the params dictionary (or whatever it is now). While (arguably) having params itself never be null is desirable, testing for items in it is required.

**Comment by ahmednawar** [comment] 2016-08-31 17:03
@francisjervis that's weird. I will try to to reproduce on my end and look into fixes. Since you have a head start here, did you reach any fix that I can look into as well? Do you have a PR?

**Comment by francisjervis** [comment] 2016-08-31 18:04
OK - removing the 
`if params != nil {

**Comment by ahmednawar** [comment] 2016-08-31 19:16
@francisjervis you will always get an error object if there is any issue like no network connectivity and the params will be an empty dictionary (but not `nil`). Could you please test that this is the case by putting your phone on Airplane mode and check for the response from Branch?

**Comment by ahmednawar** [comment] 2016-09-08 16:58
@francisjervis I am closing here but feel free to re-open if you encounter any issues. Cheers!

**Closed by ahmednawar** 2016-09-08 16:58 UTC
