### ISSUE TITLE
BUO [keywords] not working properly

### ISSUE THREAD

**Issue by francisjervis** [BranchMetrics/ios-branch-deep-linking#471] opened 2016-09-29 19:13 UTC
Hi, I am seeing some unusual errors after updating to Swift 3 with the current SDK (0.12.11). Passing an array of keywords when creating a BUO now results in "Cannot encode value Optional("somestring"), type is not in list of accepted types". This is unexpected given that the array of unwrapped strings being passed is also not itself an optional type.

**Comment by aaustin** [comment] 2016-09-30 10:14
@francisjervis - That's super weird. Can you share your swift 3 code snippet for passing them in so that we can easily reproduce on our end? Thanks for the feedback!

**Comment by francisjervis** [comment] 2016-09-30 18:16
```
var branchObject: BranchUniversalObject = BranchUniversalObject()
let keywords = ["coop", "sharing", exchangeText!, self.exchangeServiceText.text!]
self.branchObject.canonicalIdentifier = self.newExchange.objectId!
self.branchObject.title = exchangeName
self.branchObject.contentDescription = exchangeText!
self.branchObject.imageUrl = String(describing: imageUrl)
self.branchObject.keywords = keywords

self.branchObject.registerView()
```

**Comment by aaustin** [comment] 2016-10-03 09:23
Heyo - So, playing around a bit in our Swift 3 testbed on iOS 10, I can't reproduce with actual strings:
```branchUniversalObject.keywords = ["coop", "sharing", "test123"]
```

Is it possible that `exchangeText` or `self.exchangeServiceText.text` are optionally null or something? Perhaps the array is barfing on those types? To be honest, I'm not super familiar with the typing system in Swift.

**Comment by E-B-Smith** [comment] 2016-10-26 23:37
I can't reproduce this either.  Is there any more information on this?  I'll close this in a few days unless I hear back.

**Closed** 2016-11-04 20:38 UTC
