### ISSUE TITLE
showShareSheetWithLinkProperties crashes

### ISSUE THREAD

**Issue by YotamGolomb** [BranchMetrics/ios-branch-deep-linking#461] opened 2016-09-20 17:51 UTC
getting 

>  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

when calling in swift (2.2) 
    public func showShareSheetWithLinkProperties(linkProperties: BranchLinkProperties?, andShareText shareText: String?, fromViewController viewController: UIViewController?, completion: shareCompletion?)

all parameters that are needed for the function aren't nil.
when reverted to 0.12.6 , works like a charm

**Comment by aaustin** [comment] 2016-09-21 02:49
Hey @YotamGolomb - This is super weird. Would you mind sharing the code you're using to initialize link properties and the Branch universal object? For example, I recently learned that Swift supports nils in objects but Objective C doesn't. You could be putting a secret nil bomb inside an array somewhere for us.

Thanks for your help!

**Comment by YotamGolomb** [comment] 2016-09-21 06:14
let shareText = NSLocalizedString("Download the app to join our community\n", comment: "InviteToApp.ShareText")
    let branchUniversalObject: BranchUniversalObject = BranchUniversalObject(title: NSLocalizedString("App Invitation", comment: "InviteToApp.Title"))!
    branchUniversalObject.contentIndexMode = .Public

    let linkProperties: BranchLinkProperties = BranchLinkProperties()
    linkProperties.feature = "sharing"
    linkProperties.channel = "my_app"

    branchUniversalObject.contentDescription = NSLocalizedString("install the app in order to get in.", comment: "InviteToApp.ContentDescription")
    branchUniversalObject.imageUrl = self.iconUrl?.absoluteString
    branchUniversalObject.addMetadataKey(BRANCH_INIT_KEY_CAMPAIGN, value: "Invite_to_app")

    linkProperties.addControlParam("$email_subject", withValue: NSLocalizedString("Come join the app", comment: "InviteToApp.EmailSubject"))

    branchUniversalObject.showShareSheetWithLinkProperties(linkProperties, andShareText: shareText, fromViewController: vc) { (activityType, completed) in
      guard let completion = completion else { return }
      completion(activityType, completed)
    }

**Comment by aaustin** [comment] 2016-09-26 15:33
Hey @YotamGolomb - We're having some troubles reproducing in our swift testbed app. You can see the above PR, but I don't believe it's the root cause as it'd be impossible for that to happen. Tell me if this is happening 100% of the time or if it's random, perhaps during internet connectivity issues?

**Comment by leoneparise** [comment] 2016-10-06 01:10
I'm having the same issue here but with Swift 2.2. My code:
```swift
let branch = BranchUniversalObject()
branch.contentIndexMode = .Public
branch.title = "Quotes with delight"
branch.contentDescription = "Check this app out! You can combine awesome quotes with beautiful images!"
let properties = BranchLinkProperties()
properties.feature = "appInvite"
properties.channel = "kuoter"
properties.addControlParam("$ios_deepview", withValue: "branch_default")
properties.addControlParam("$android_deepview", withValue: "branch_default")

branch.showShareSheetWithLinkProperties(properties, andShareText: "Install Kuoter", fromViewController: parent, completion: nil)
```

I installed from Carthage (v0.12.11). I don't know if it is an issue.

**Comment by leoneparise** [comment] 2016-10-06 01:38
FYI, I solve the issue this way:

```swift
class AppLinkManager: NSObject {
    static func itemsForAppInviteShare() -> [AnyObject]? {
        let branch = BranchUniversalObject(title:"Quotes with delight")
        let shareText = "Install Kuoter"
        branch.contentIndexMode = .Public
        branch.contentDescription = "Check this app out! You can combine awesome quotes with beautiful images!"
        
        let properties = BranchLinkProperties()
        properties.feature = "appInvite"
        properties.channel = "kuoter"
        properties.addControlParam("$ios_deepview", withValue: "branch_default")
        properties.addControlParam("$android_deepview", withValue: "branch_default")
        
        if let item = branch.getBranchActivityItemWithLinkProperties(properties) {
            return [shareText, item]
        } else {
            return nil
        }
    }
}
```

Then I construct the `UIActivityViewController` this way:
```swift
if let parent = self.navigationController, let items = AppLinkManager.itemsForAppInviteShare() {
    let shareVC = UIActivityViewController(activityItems: items, applicationActivities: nil)
    parent.presentViewController(shareVC, animated: true, completion: nil)
}
```

Now it's working like a charm =)

**Comment by zeeshabnc** [comment] 2016-10-23 16:42
Thanks @leoneparise. Closing this out for now, do re-open it if this is still an issue for you.

**Closed by zeeshabnc** 2016-10-23 16:42 UTC
