### ISSUE TITLE
Inconsistent Link attribution in Branch.initSession()

### ISSUE THREAD

**Issue by johnemiller** [BranchMetrics/ios-branch-deep-linking#851] opened 2018-08-07 21:30 UTC
Hello -

We are seeing inconsistent Branch link attribution in our app with respect to Branch's SDK reliably passing back the utm params and other metadata associated with a Branch marketing link which trigger's app installation through the Apple Appstore and/or our own internal staging distribution server (HockeyApp).  Specifically, what we see is that on some test devices, attribution always occurs reliably and after the user clicks a link and installs the app when Branch.initSession() is invoked, the param set always contains all of the standard and custom attribution data that we'd expect to see and it successfully gets pushed into Segment.io via a custom track event that we fire.  

On another set of users/devices, we very rarely get successful attribution and the "clicked_branch_link" attribute of the payload returned in Branch.initSession() always shows "false" and as such, none of the link attribution data is there either.  There does not seem to be any pattern to which devices consistently don't work vs those that do or which iOS versions, etc.

The steps that we follow for testing/verifying this scenario in our app are:

1.  uninstall all previously installed versions of [Our App] (staging or production);

2.  create a note with the following link on the test device (or add the following link to an existing note): 

https://[redacted].test-app.link/kgGB9gaoWN?utm_source=facebook&utm_campaign=staginginstalltest

3.  go to Settings>Privacy>Advertising and click "Reset Advertising Identifier...";

4.  click on the link created in step 2.  You should be redirected to HockeyApp|AppStore to download the staging or the AppStore app version, depending on the specific link that is being used;

5.  click "Install" on the HockeyApp/AppStore distribution landing page;

6.  If you are testing an Enterprise (HockeyApp distribution) build go to Settings>General>Profiles & Device Management>Enterprise [Our Company].  Click "Trust [Our Company] (ENT)";

7.  open Segment's staging|production app dashboard: 

https://app.segment.com/[OUR COMPANY]/sources/events-[staging or production]/debugger

8.  Open the newly installed staging|appstore app version.  Once the app opens, background it by hitting the "Home" button, or swiping up on iPhoneX devices;

In successful attribution cases, we see something like (below) associated with the custom track event that is logged in the Segment.io debugger:

[[SEGAnalytics sharedAnalytics] track:@"Install Attributed", properties: @{
    @"$ios_url" : @"https://rink.hockeyapp.net/apps/h123h4h1234h123h4h1234h123",
    @"$marketing_title" : @"John.Miller iOS Test Link",
    @"$og_description" : @"Blah, Blah, Blah, Blah",
    @"$og_title" : @"Test Install Link",
    @"$one_time_use" : @false,
    @"+click_timestamp" : @1533180457,
    @"+clicked_branch_link" : @true,
    @"+is_first_session" : @true,
    @"+match_guaranteed" : @false,
    @"anonymousId" : @"XXX-XXX-XX-XXXX-XXXXX-XXXX",
    @"category" : @"Sign Up",
    @"name" : @"Marketing Attribution Test Campaign",
    @"platform_type" : @"iOS",
    @"source" : @"Github",
    @"utm_campaign" : @"staginginstalltest",
    @"utm_source" : @"facebook",
    @"~campaign" : @"Marketing Attribution Test Campaign",
    @"~channel" : @"Github",
    @"~creation_source" : @1,
    @"~feature" : @"marketing",
    @"~id" : @"XXXXXXXXXXXXXXXXXXXXXXX",
    @"~marketing" : @true,
    @"~referring_link" : @"https://[redacted].test-app.link/kgGB9gaoWN?utm_source=facebook&utm_campaign=staginginstalltest"
}];

In the cases where attribution does not work, the data associated with the custom track event in Segment.io is:

[[SEGAnalytics sharedAnalytics] track:@"Install Attributed", properties: @{
    @"+clicked_branch_link" : @false,
    @"+is_first_session" : @true,
    @"anonymousId" : @"XXXXXX-XXXXXX-XXXXXX-XXXXX-XXXXXX-XXXX",
    @"category" : @"Sign Up",
    @"platform_type" : @"iOS"
}];

We've already spent some time working with our Branch technical liason (Brian Chang) on this, so he may be able to provide some relative context for you as well.  Also, per Brian's suggestion, we flipped the initialization order for all of our analytics SDKs to ensure that Branch is the first one initialized to ensure that it wasn't a case of another SDK consuming the attribution data prior to Branch.  This did not have any effect on the issue manifesting itself.

Any assistance/insight would be greatly appreciated as this is making it virtually impossible for our marketing team to intelligently ascertain the impact of our various marketing campaigns.

**Comment by E-B-Smith** [comment] 2018-08-07 23:09
Thanks for writing in about this.

I am updating the SDK for better Segment integration right now and that may fix your issue.

I'll update you when that fix is ready.

**Comment by TinananaWang** [comment] 2018-08-07 23:36
@E-B-Smith Thank you for the prompt reply!

Just would like to note here that this issue is very urgent for our company, and can we please get a time estimate for fixing that Segment Integration issue? 

Also, our main problem is, we are not seeing those UTM attributions even in the Branch debugger. Would it be possible that this issue also lies within Branch?

Thank you so much for your help and hope to hear from you soon.

**Comment by E-B-Smith** [comment] 2018-08-08 00:27
I should have a fix for this on Wednesday.

For UTM attribution, unfortunately we only show it certain cases now, but are working on showing it in all cases.  I'll ask about the status of this.

**Comment by TinananaWang** [comment] 2018-08-08 00:52
> I should have a fix for this on Wednesday.

Awesome. Thank you!

> For UTM attribution, unfortunately we only show it certain cases now, but are working on showing it in all cases. I'll ask about the status of this.

Yes, we can see UTM on some device/some times, but not consistent at all. Overall 20 - 30% tests have UTMs. Would be great if this is more consistent. Appreciate any update on status/time estimate for this issue. Thank you!

**Comment by TinananaWang** [comment] 2018-08-09 22:06
@E-B-Smith 
> I should have a fix for this on Wednesday.

> For UTM attribution, unfortunately we only show it certain cases now, but are working on showing it in all cases. I'll ask about the status of this.

May I follow up with the status of the two issues above, please? Appreciate your help.

**Comment by E-B-Smith** [comment] 2018-08-09 23:40
I am testing the fixes to our SDK now, which is unfortunately taking longer than expected.

I'll follow up here when I have a fix.

**Comment by TinananaWang** [comment] 2018-08-10 01:33
>I am testing the fixes to our SDK now, which is unfortunately, taking longer than expected.
I'll follow up here when I have a fix.

Got it. 

How about the issue of inconsistent UTM attibution in the Segment Debugger? This might solve our main concern. Thank you!

**Comment by Sarkar** [comment] 2018-08-10 17:39
@TinananaWang I can help with the UTM attribution question. Are you using dynamic Branch links (links with query parameters), or regular quick links?

**Comment by TinananaWang** [comment] 2018-08-10 18:37
@Sarkar We are using Dynamic- with query params. Appreciate the help!

**Comment by E-B-Smith** [comment] 2018-08-13 17:28
@TinananaWang 

I've made a new release of the iOS SDK that will prevent double app opens from being sent when using Segment.

To upgrade to the latest version using CocoaPods, do a `pod update` on your project.

**Comment by maetuck** [comment] 2018-08-14 15:31
@Sarkar @TinananaWang We are using both dynamic branch links and ad links and still getting inconsistent attribution. Would appreciate guidance on how to ensure that UTM parameters are passing through 100% of the time.

**Comment by TinananaWang** [comment] 2018-08-16 21:02
Hi @Sarkar Thanks for the information.

Here is one of our live ad links:
https://XXXX.app.link/j0eyXhs71O?%243p=a_facebook&utm_source=facebook&utm_medium=org&utm_campaign=VF-ORG-MobileAppInstalls&utm_content=LA-DMA-iOS-PLL1-W35-54&utm_term=MDV2

Based on the format you provided for dynamic ad links:
your-domain.app.link/$3p=a_<partner_key>&utm_source=source&utm_channel=channel.

Here is the dynamic ad link I created:
https://XXXX.app.link/$3p=a_facebook&utm_source=facebook&utm_medium=org&utm_campaign=VF-ORG-MobileAppInstalls&utm_content=LA-DMA-iOS-PLL1-W35-54&utm_term=MDV2

@Sarkar Can you please help us verify this link format is right? 
Also, is there any additional steps that we need to do in addition to the ones that you described above, or we can just use the link directly?

Thank you and hope to hear from you soon.

**Comment by maetuck** [comment] 2018-08-16 21:26
@Sarkar in our link settings, i've enabled "use UTM tags for analytics" but "enable link scraping" is currently disabled. should we enable that as well?

**Comment by sophylee** [comment] 2018-08-16 21:44
@Sarkar this is Sophy, also from Mae and Tina's team. To summarize Tina's question, using the format you provided `facebook` would be our `partner_key`. This doesn't seem right given a key seems like it should be something custom to our company. We'd also want to use this dynamic link across a variety of ad platforms. Given all that, are we sure that `your-domain.app.link/$3p=a_<partner_key>&utm_source=source&utm_channel=channel.` is the link format we should be using? 

Re: the second part of your response, 

> Essentially, you'll need to make sure you find the partner_key - this is present on all ad links created. If you are not using an app.link domain, you'll need to attach /a/<your_branch_key>, and then continue adding the UTM query parameters.

we are using an `app.link` domain so it seems like this doesn't apply to us.

**Comment by Sarkar** [comment] 2018-08-17 22:54
@sophylee sorry for the delay in response. If you're using app.link, then my solution above is OK. In addition, partner key is unique to Branch. So, for your link, it'd be $3p=a_fb (facebook). That being said, I understand that you must be using Facebook App Install ads. Is that the case? If so, the requirements and UTM logic is somewhat different.

Would you be open to a quick chat over email, slack, or phone? I think this might be quicker -- I'm at sahil@branch.io, feel free to send a msg there and we can coordinate something to a quicker solution.

@maetuck you don't need to check mark "enable link scraping".

**Comment by TinananaWang** [comment] 2018-08-17 23:17
@Sarkar Thank you for the respond, and yes, we are using Facebook App Install ads.

Since this issue is very urgent for our team, we would appreciate a phone/video call with you early next week, if possible. I will email you shortly with our available timeslots. Thank you!

**Comment by E-B-Smith** [comment] 2018-08-21 20:48
@Sarkar @TinananaWang 

Did this get resolved?

**Comment by TinananaWang** [comment] 2018-08-22 04:56
@E-B-Smith Thanks for checking in. Yes, we are working with @Sarkar regarding the dynamic link. We have just verified that the new link is working and it gives us the expected UTM in Branch (Thanks @Sarkar!). 

We are now testing the SDK in staging and checking UTM in Segment. Here is out test link: https://cm2v.test-app.link?$3p=a_facebook&utm_campaign=some_campaign&utm_source=some_source&$ios_url=https://rink.hockeyapp.net/apps/67cf1e34766347cea6a1f0c0df01d3ed&$android_url=https://play.google.com/store/apps/details?id=com.hopskipdrive.hsd_android_v2.beta&$desktop_url=https://organizer.hopskipdev.com/sign-up.

Device 1 (iPhoneX) - 4 tests. First Two of them had UTM. Clicked_branch_link = true
<img width="1411" alt="succeed utm" src="https://user-images.githubusercontent.com/20799093/44441904-dd7c2680-a583-11e8-9266-69a9b956857f.PNG">

While two of them do not have UTM. Clicked_branch_link = false
<img width="1448" alt="failed utm" src="https://user-images.githubusercontent.com/20799093/44441909-e7058e80-a583-11e8-8abf-7944d3e3c407.PNG">

Device 2 (iPhone 6s) also only succeeded in the first 2 trials and failed the next two.

Reproducing Steps are the same as the ones in main ticket created by John. @E-B-Smith Please let us know whether this is supposed to be so (only supposed to succeed first two installs), or it is still under development. Meanwhile, we will test more devices. Thank you and hope to hear from you soon.

**Comment by TinananaWang** [comment] 2018-08-22 18:35
@E-B-Smith We can add you to Hockey if you need to be able to reproduce the issue. Please provide your email information, and please let us know if you need anything else from our side. Thank you!

**Comment by E-B-Smith** [comment] 2018-08-22 18:43
I notice your link:

```
https://cm2v.test-app.link?$3p=a_facebook&utm_campaign=some_campaign&utm_source=some_source&$ios_url=https://rink.hockeyapp.net/apps/67cf1e34766347cea6a1f0c0df01d3ed&$android_url=https://play.google.com/store/apps/details?id=com.hopskipdrive.hsd_android_v2.beta&$desktop_url=https://organizer.hopskipdev.com/sign-up.
```

Has a second question mark in the URL in this part: `details?id=com.hopskipdrive`. The second part of the URL needs to be URL encoded or it will be misinterpreted by some URL parser somewhere.

This could be your problem.

**Comment by TinananaWang** [comment] 2018-08-22 21:11
@E-B-Smith 
Please verify the format of this URL encoded link is correct:
https://cm2v.test-app.link?%243p%3Da_facebook%26utm_campaign%3Dsome_campaign%26utm_source%3Dsome_source%26%24ios_url%3Dhttps%3A%2F%2Frink.hockeyapp.net%2Fapps%2F67cf1e34766347cea6a1f0c0df01d3ed%26%24android_url%3Dhttps%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.hopskipdrive.hsd_android_v2.beta%26%24desktop_url%3Dhttps%3A%2F%2Forganizer.hopskipdev.com%2Fsign-up

I have just tested once - No UTM in Segment. If the format is not accurate, please guide us in how to make a working testing link. The production link is https://cm2v.app.link?$3p=a_facebook&utm_campaign=some_campaign&utm_source=some_source&$ios_url=https://itunes.apple.com/us/app/hopskipdrive/id950823144?mt=8&$android_url=https://play.google.com/store/apps/details?id=com.hopskipdrive.hsd_android_v2&$desktop_url=https://organizer.hopskipdrive.com/sign-up

Thank you

**Comment by TinananaWang** [comment] 2018-08-22 21:15
Also, @E-B-Smith On Aug 13, you mentioned: 
>I've made a new release of the iOS SDK that will prevent double app opens from being sent when using Segment.

However, our problem is: inconsistent UTM tracking in Segment. Would this release help solve our question? Thanks.

**Comment by E-B-Smith** [comment] 2018-08-22 21:35
Here is your URL correctly query parameter escaped:

https://cm2v.test-app.link?%243p=a_facebook&utm_campaign=some_campaign&utm_source=some_source&%24ios_url=https%3A//rink.hockeyapp.net/apps/67cf1e34766347cea6a1f0c0df01d3ed&%24android_url=https%3A//play.google.com/store/apps/details%3Fid%3Dcom.hopskipdrive.hsd_android_v2.beta&%24desktop_url=https%3A//organizer.hopskipdev.com/sign-up

**Comment by TinananaWang** [comment] 2018-08-22 22:49
@E-B-Smith Thanks. 
I tested on the above link three times. Succeed in the first trial but failed for the other two. Still inconsistent passing of UTMs to Segment.

**Comment by TinananaWang** [comment] 2018-08-23 19:43
@E-B-Smith Can we please schedule a call regarding this integration issue? It might help speed up the process. Thank you.

**Comment by E-B-Smith** [comment] 2018-08-23 20:26
I've tested clicking on Branch links with utm parameters and they consistently open the app and return the expected data: The campaign, source, and $3p parameters were set.  I clicked on the links a number of times and they worked each time.

This doesn't seem to be a bug in the SDK but an issue with how the how the links are used or some Segment configuration issue.

• Where are you posting these links? On Facebook, email, or the web? Some of these channels will strip or modify parameters in a URL.
• What have you done to try and debug the issue?
• Have you set a break point in the app when the deep link is received?

**Comment by E-B-Smith** [comment] 2018-08-23 20:52
Also, have you added these lines to your app delegate:

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    [[Branch getInstance] handleDeepLink:url];
    return YES;
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void (^)(NSArray *))restorationHandler {
    [[Branch getInstance] continueUserActivity:userActivity];
    return YES;
}
```

Sometimes Segment doesn't forward those messages to Branch correctly.

**Comment by TinananaWang** [comment] 2018-08-23 22:59
@E-B-Smith 
> I've tested clicking on Branch links with utm parameters and they consistently open the app and return the expected data: The campaign, source, and $3p parameters were set. I clicked on the links a number of times and they worked each time.
This doesn't seem to be a bug in the SDK but an issue with how the how the links are used or some Segment configuration issue.

If you are talking about UTMs in Branch, then this is right. We do see consistent UTMs in Branch
> Where are you posting these links? On Facebook, email, or the web? Some of these channels will strip or modify parameters in a URL.

The link that I sent you is the test link. Partner key is facebook.

> What have you done to try and debug the issue?

- I am not sure I fully understand this question. Our engineer @johnemiller has set up a new SDK and I tested using your link with the steps on the main ticket. UTMs in Branch but not in Segment. 
- No debugging from our engineering team.

> Have you set a break point in the app when the deep link is received?

No.

> Also, have you added these lines to your app delegate

 Yes, those two methods are (and have been) implemented for quite a while now.

Does these answer all your questions? Please let us know what other information you need, or what can we do/modify in order to see UTM in Segment. Thank you!!

**Comment by TinananaWang** [comment] 2018-08-24 19:31
@E-B-Smith Also, I know we are trying to solve the Branch <> Segment Integration here. But I just learned from @Sarkar about [this document](https://docs.branch.io/pages/integrations/segment/), and we are considering setting this up. 

May I learn about the relationship between your new SDK and this new document:
- Is this new SDK a pre-requisite for this feature?
- Am I right to say that we have to set up both this feature and the new SDK for 100% accurate UTM parameter passing? 

Thank you!!

**Comment by E-B-Smith** [comment] 2018-08-26 21:41
I've tested with the Segment-Branch SDK integration and I can see that Branch is getting the utm values from my test links in our dashboard, so things are hooked up and the data is there.

I don't know how Segment handles this data, Segment is the expert on Segment (I'm a Branch engineer!), so you will probably get better answers if you talk to them directly.

The Segment-Branch server-to-server integration may help. 

So my advice is to talk to Segment and see if they can help.

**Closed by E-B-Smith** 2018-08-26 21:41 UTC
Labels: responded

**Comment by TinananaWang** [comment] 2018-08-27 04:53
Ok. Thank you.
