### ISSUE TITLE
Universal Link Display Multiple Dialogs to User

### ISSUE THREAD

**Issue by msalmanST** [BranchMetrics/ios-branch-deep-linking#781] opened 2018-02-08 14:56 UTC
**IOS 10.X With App Not Installed**

When I open a universal link from IOS Gmail client then it redirects me to some branch url and show me two prompts,

1. First prompt say "Safari cannot open the page because the address is valid" with Okay button.
2. Upon clicking the okay another prompt become visible with message "Open this page in App Store"

**IOS 10.X With App Installed**

When I open a universal link from IOS Gmail client then it redirects me to some branch url and show me two prompts,

1. First prompt say "Open this page in MyApp" with Okay and Cancel buttons.
2. Upon clicking the Okay it takes me to my app.
3. Upon clicking the Cancel button another prompt become visible with message "Open this page in App Store".

I am also facing some weird issues on IOS 11 when testing a link or default email client / gmail client / safari I guess those issues relates with #766

**Comment by E-B-Smith** [comment] 2018-02-08 17:44
Thanks for writing in.

#### iOS 10.X With App Not Installed

This case is caused by setting the `$uri_redirect_mode` in the link. Try setting the value to `1`, smart redirect mode, which might mitigate this. You may need to reset your privacy settings to test this as a new user:   Settings > Privacy > Advertising > Reset Advertising Identifier .

#### iOS 10.X With App Installed

In iOS, the operating system always gives the user the choice to open a link in an app or not, so the dialogue is always shown. That's an operating system thing and there's not much we can do about it.

I think the user interaction in the the two cases are correct.

**Comment by E-B-Smith** [comment] 2018-02-14 22:28
I am going to close this out now.  If you are still having issues please reopen this issue or contact support@branch.io.

Thanks!

**Closed by E-B-Smith** 2018-02-14 22:28 UTC
